### ISSUE TITLE
Add missing updatecli manifests to keep track of new Docker images versions

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#64]
Currently, only a part of [the charts](https://github.com/jenkins-infra/helm-charts/tree/main/charts) have a corresponding [updatecli manifest](https://github.com/jenkins-infra/helm-charts/tree/263b62c4cfd1819fe9b8cb9c33116ed4391b4432/updatecli/updatecli.d) to keep track of their docker images versions.

All of them should be covered to avoid manually bumping them like here: https://github.com/jenkins-infra/helm-charts/pull/38

**Comment by dduportal** [comment]
- #77 is related to this task

Not sure what other images?

**Comment by vihaanthora** [comment]
Hello @lemeurherve, can I work on this issue?
Regards

**Comment by dduportal** [comment]
Hello @vihaanthora , you are welcome to work on this task!

We only ask you to update the issue here with your plans before sending pull requests.

Let us know if you need help.

**Comment by vihaanthora** [comment]
Thank you @dduportal. I wanted to know if the other branches in the repository carry any significance, or should I just focus on the main branch? From what I understand, I have to create corresponding .yaml files of the charts in updatecli/updatecli.d (21 in total). I can look up the template from the pre existing files. Is there any source from where I can find out the values that must go in each of these files.
Thanks

**Comment by dduportal** [comment]
Hello @vihaanthora , the updatecli manifest that you (might?) have to add are only focused on tracking dependencies of the form "external docker image" which name/tag are specified in a chart of this repository).

So the first part of the work, before adding code, is to list, in this issue, these docker images.

Have a look at #77 as an example.

=> Maybe the conclusion would be "all images are already track, no need for more".

**Comment by vihaanthora** [comment]
@dduportal The issue states that all the charts need a corresponding updatecli manifest.

> All of them should be covered to avoid manually bumping them like here: #38

According to this, there are indeed charts such as acountapp, acme, basic-helm-chart-example, etc.  that do not have updatecli manifests to update their docker image versions. I am not sure how all images are already track. I am new to this codebase so I might be missing something important. Please let me know.
Regards

**Comment by dduportal** [comment]
> @dduportal The issue states that all the charts need a corresponding updatecli manifest.
> 
> > All of them should be covered to avoid manually bumping them like here: #38
> 
> According to this, there are indeed charts such as acountapp, acme, basic-helm-chart-example, etc. that do not have updatecli manifests to update their docker image versions. I am not sure how all images are already tracked. I am new to this codebase so I might be missing something important. Please let me know. Regards

Let me show you some example (I think you understood but I'm showing example to be sure that the we are clear on the task :) ):

- Let's look at the manifest https://github.com/jenkins-infra/helm-charts/blob/cd25600057bd4af8fe1ad4f47a6b7327b535260f/updatecli/updatecli.d/custom-distribution-service.yaml which already exist: it tracks the version of the Docker image `jenkinsciinfra/custom-distribution-service` which is defined in the default values of the helm chart at https://github.com/jenkins-infra/helm-charts/blob/main/charts/custom-distribution-service/values.yaml#L6-L8
  - There are no other Docker image specified in this chart `custom-distribution-service`: hence no additional work is required for this one.

- Now let's look at the chart `accountapp` (which I recommend you to start with), in particular its default values: https://github.com/jenkins-infra/helm-charts/blob/main/charts/accountapp/values.yaml#L8
  - A Docker image is specified: `jenkinsciinfra/account-app`
  - But there is no explicit tag defined. It means that it is not tracked: it needs to be defined (at least to `latest` for starting) and then add an updatecli manifest that would track and update this tag version.
  - The most difficult part is to search for the "source" of version: in the case of accountapp, it's in https://github.com/jenkins-infra/account-app => this one is not an easy one because it is not versionned (hence the implicit `latest` tag).


=> That's why a first step of "listing images" and for each image checking if it already tracked and if it is possible to track it.

**Comment by vihaanthora** [comment]
Thank you so much for the in-depth explanation @dduportal, I really appreciate it. 
Apart from `acountapp`, I found out that `ircbot` is also not tracked. All others have some tags associated with the images. 

Some things I noticed - 
- The latest image `jenkinsciinfra/wiki` is tagged as `latest` on docker, which means we can simply mention `"latest"` in the [tag ](https://github.com/jenkins-infra/helm-charts/blob/cd25600057bd4af8fe1ad4f47a6b7327b535260f/charts/wiki/values.yaml#L10) and remove its updatecli manifest altogether as done [here](https://github.com/jenkins-infra/helm-charts/blob/cd25600057bd4af8fe1ad4f47a6b7327b535260f/charts/plugin-site-issues/values.yaml#L11). Similar thing could be done to all images which are pushed with the tag `latest` as the most recent tag.
- The [latest](https://hub.docker.com/r/jenkinsciinfra/account-app/tags) tag of `acountapp` is `215-buildca55e3`.
- The [latest](https://hub.docker.com/r/jenkinsciinfra/ircbot/tags) tag of `ircbot` is `214-builde2b839`, and it is versioned (unlike `accountapp`), and the [latest](https://github.com/jenkins-infra/ircbot/releases/tag/v1.5.0) version is `1.5.0`.

Please let me know if you find any of the above mentioned observations to be inconsistent. If everything seems alright, what would be the next point of action?
Regards

**Comment by vihaanthora** [comment]
Any update on this issue?

**Comment by dduportal** [comment]
> Any updates on this issue?

Sorry @vihaanthora I'm off this week: you will have an answer next week.

**Comment by vihaanthora** [comment]
No worries @dduportal, please take your time!

**Comment by dduportal** [comment]
Hello @vihaanthora , sorry for the looong delay, it was not sustainable for us to work on this.

But now it is ok. If you are still willing to contribute, you can start working on it again.

- First of all, please be carefull to open a pull request per updatecli manifest to add: some manifest will be easy, while other will require discussion and could be delayed or not accepted (because legacy applications, because specific use case for instance).
- I did not check toroughly but you can assume that each helm-chart in this repository involving a docker image (deployment or statefulset in the templates), the image should be under the DockerHub organization `jenkinsciinfra`. 

- Each Docker image stored within the DockerHub organization `jenkinsciinfra` has its source stored within a github repository in the GitHub organization [jenkins-infra](https://github.com/jenkins-infra).
  - We have an exhaustive list of these repositories defined (Jenkins jobs in charge of building/releasing these images to DockerHub) [here](https://github.com/jenkins-infra/kubernetes-management/blob/main/config/ext_jenkins-infra-jobs.yaml#L20-L39). Their name should be prefixed by `docker-`.
  - My personal "trick" is to search for the string `imageName` in the `Jenkinsfile*`: https://github.com/search?l=Groovy&q=org%3Ajenkins-infra+imageName&type=Code to ensure that a given repository generates a given Docker image.

- The default process (except for some edge cases: open your PRs and we'll do it case by case) for the updatecli manifests is:
  - Retrieve the latest GitHub release (or tag) associated to the source of the Docker image as "updatecli source"
  - Check that there is a Docker image with this tag ("updatecli condition") to avoid opening PR when the tag was created on GitHub but not yet released on the DockerHub
  - Update the corresponding Helmchart (with the automatic version)

- For some images, such as accountapp and ircbot (as you guessed), the pattern is to use the "latest". In that case, we should:
  - Retrieve the sha digest of the latest docker image (rebuilt weekly to benefit from latest base image patches)
  - No need for a condition
  - Update the helm chart (be careful to add the "@sha256" suffix to the image name)

----

> - The latest image jenkinsciinfra/wiki is tagged as latest on docker, which means we can simply mention "latest" in the [tag ](https://github.com/jenkins-infra/helm-charts/blob/cd25600057bd4af8fe1ad4f47a6b7327b535260f/charts/wiki/values.yaml#L10)and remove its updatecli manifest altogether as done [here](https://github.com/jenkins-infra/helm-charts/blob/cd25600057bd4af8fe1ad4f47a6b7327b535260f/charts/plugin-site-issues/values.yaml#L11). Similar thing could be done to all images which are pushed with the tag [latest](https://hub.docker.com/r/jenkinsciinfra/account-app/tags) as the most recent tag.
> - The [latest](https://hub.docker.com/r/jenkinsciinfra/ircbot/tags) tag of acountapp is 215-buildca55e3.
> - The [latest](https://github.com/jenkins-infra/ircbot/releases/tag/v1.5.0) tag of ircbot is 214-builde2b839, and it is versioned (unlike accountapp); the latest version is 1.5.0.
   
To answer your questions:

- Image `jenkinsciinfra/wiki: tags are created but not deployed to DockerHub, which is weird. Working on it in https://github.com/jenkins-infra/helpdesk/issues/2887
- About accountapp and ircbot, I propose to use the "digest" method

Sounds good to you?

**Comment by vihaanthora** [comment]
Thanks for getting back, I am currently tied up with my semester examinations, and I will try to get back to this after it finishes. Till then, anyone else who wishes to contribute to this issue is welcome to start. 
Regards

**Comment by dduportal** [comment]
Closed by #224
