### ISSUE TITLE
Bugfix: stop the never ending loop with updatecli

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helm-charts#78]
Each execution of updatecli bumps the helm chart version of each manifest and keeps opening/updating pull request. It's a nightmare to maintain.

I'm not sure if it is a misconfiguration or a bug in updatecli.

Ping @olblak we need your expertise on that part

**Comment by lemeurherve** [comment]
The loop was due to the fact I was specifically bumping the chart version by default in one source, and retrieve a possible new docker image version. Since there were always a modified target with this bumped source, updatecli always opened new PRs.
Using target `helmChart` type instead of `yaml` resolves it in #83
